version: '3'

services:
  elasticsearch:
    build:
      context: ./elasticsearch
    image: elasticsearch:7.2.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - 5601:5601
